# Uppdatera scripts/pubspec.yaml

name: package_updater
description: Script to update package list from pub.dev
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.0
  html: ^0.15.4
  yaml: ^3.1.0